### ISSUE TITLE
paragraph tag outputs as padding in "Expand Abbreviation" and "Wrap with Abbreviation" functions

### ISSUE THREAD

**Issue by geoffa** [sergeche/tea-for-coda#1]
Typing the following line:
    div>p.message

Results in the following:
    <div>
        padding:;
    </div>

This happens in both the "Expand Abbreviation" and "Wrap with Abbreviation" functions. It seems like it should produce the following output:
    <div>
        <p class="message"></p>
    </div>

Coda version 1.6.7. OS X version 10.5.7

Thanks for taking a look.
-geoff

**Comment by sergeche** [comment]
Please re-download Coda plugin: http://cloud.github.com/downloads/sergeche/tea-for-coda/TEA_for_Coda.codaplugin.zip
I've fixed thix issue

**Comment by geoffa** [comment]
Thanks for the prompt response. I just tried to re-download the plugin and the issue remains. Thanks again!

**Comment by geoffa** [comment]
You can close this. Downloaded and built for source and this works now. Perhaps the .zip needs to be updated? Thanks for working on a great project.

**Comment by sergeche** [comment]
Well, I've updated zip yesterday, downloaded today and this bundle worked as a charm. Don't know where the problem is

**Comment by geoffa** [comment]
This is working now. Maybe all the deleting of the plug-in, redownloading, restarting Coda, etc. Got it to work. Regardless, thanks again for such a great plugin. Sorry for any inconvenience.

**Comment by sergeche** [comment]
Issue is fixed
